version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./results:/app/results
    